import Head from "next/head";

import styles from "./index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>St Pete Tennis Series</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            St Pete <span className={styles.pinkSpan}>TENNIS</span> Series
          </h1>
        </div>
      </main>
    </>
  );
}
